language: ruby
rvm:
  - 1.9.3
before_script:
  - bundle exec rake db:drop db:create db:migrate db:test:prepare
  #- "psql -c 'create database codemarks_test;' -U postgres"
  #- "export DISPLAY=:99.0"
  #- "sh -e /etc/init.d/xvfb start"
#script:
#  - bundle exec rspec spec
