language: ruby
rvm:
  - 1.9.3
before_script:
  - bundle exec rake db:drop db:create db:migrate db:test:prepare
script:
  - bundle exec rspec spec/fast
  - bundle exec rspec spec/lib 
  - bundle exec rspec spec/controllers spec/integration spec/models
  - bundle exec cucumber
