development:
  adapter:   postgresql
  encoding:  unicode
  database:  codemarks_development
  pool: 5
  min_messages: warning

test: &TEST
  adapter:   postgresql
  encoding:  unicode
  database:  codemarks_test
  pool: 5
  min_messages: warning

production:
  adapter:   postgresql
  encoding:  unicode
  username:  codemarks
  password:  codemarks
  database:  codemarks
  pool: 5
  min_messages: warning

cucumber:
  <<: *TEST
